### ISSUE TITLE
tidalapi v0.8.4 breaks fix_unavailable.py

### ISSUE THREAD

**Issue by notstarboard** [notstarboard/tidal-utils#10]
After updating tidalapi from v0.8.3 to v0.8.4 , I've started encountering the following error:

```
Traceback (most recent call last):
  File "/home/josh/Programs/tidal-utils/fix_unavailable.py", line 389, in <module>
    main()
  File "/home/josh/Programs/tidal-utils/fix_unavailable.py", line 372, in main
    gray_tracks = find_gray_tracks(session)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josh/Programs/tidal-utils/fix_unavailable.py", line 34, in find_gray_tracks
    tracks = session.user.favorites.tracks(limit=9999, order="ARTIST")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josh/Programs/tidal-utils/tidalenv/lib/python3.11/site-packages/tidalapi/user.py", line 690, in tracks
    params["order"] = order.value
                      ^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'value'
```

I will try to fix this soon, but the workaround in the meantime is to install tidalapi v0.8.3 istead.
